name: vuejs-medical-CICD
on:
  push:
    branches: master
    
jobs:
  build:
    runs-on: rpi
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: pm2 list
        run: pm2 list
      - name: Deploy application
        run: pm2 restart vue-app
