name: vuejs-medical-CICD
on:
  push:
    branches: master
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.17.1'
      - name: yarn install
        run: yarn install
      - name: pm2 list
        run: pm2 list
      - name: Deploy application
        run: pm2 restart vue-app
